baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My Site'
theme = "nix"


[params]
  Name = "Mike Lee"
  HeaderUsername = "mlee"
  HeaderHostname = "myWebsite"
  About = "Hi I'm Hugo and this is my website. I am a developer, writer and family man. I like developing websites using Hugo, sports, nature, photography and travel. On this websites you can expect my projects and blog posts about everything I love. Enjoy!"

  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"

[menu]
  [[menu.header]]
    identifier = "post"
    name = "posts"
    weight = 0
    url = "/posts"
